// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASDQibgoMjhv7YbhCCGSo1GGzmK914oWc',
    appId: '1:822905858076:web:c393b43d651cdc9c6c17d9',
    messagingSenderId: '822905858076',
    projectId: 'tictactoe-899b6',
    authDomain: 'tictactoe-899b6.firebaseapp.com',
    storageBucket: 'tictactoe-899b6.firebasestorage.app',
    measurementId: 'G-Z6730QVSND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxGQ90xEc8L66mpFuoH8mFc8VVkvljmE',
    appId: '1:822905858076:android:0d6c2187039dbcaa6c17d9',
    messagingSenderId: '822905858076',
    projectId: 'tictactoe-899b6',
    storageBucket: 'tictactoe-899b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATJt4JIUecIjONM-oule7mSyJA4cr6bs4',
    appId: '1:822905858076:ios:4c967f52736ce4c76c17d9',
    messagingSenderId: '822905858076',
    projectId: 'tictactoe-899b6',
    storageBucket: 'tictactoe-899b6.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATJt4JIUecIjONM-oule7mSyJA4cr6bs4',
    appId: '1:822905858076:ios:4c967f52736ce4c76c17d9',
    messagingSenderId: '822905858076',
    projectId: 'tictactoe-899b6',
    storageBucket: 'tictactoe-899b6.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASDQibgoMjhv7YbhCCGSo1GGzmK914oWc',
    appId: '1:822905858076:web:f9421326800e02c06c17d9',
    messagingSenderId: '822905858076',
    projectId: 'tictactoe-899b6',
    authDomain: 'tictactoe-899b6.firebaseapp.com',
    storageBucket: 'tictactoe-899b6.firebasestorage.app',
    measurementId: 'G-36WVTQRXML',
  );
}
